CREATE TABLE public.payment (
    id BIGINT NOT NULL,
    contexte_commande VARCHAR(255),
    currency VARCHAR(255),
    date_initiation TIMESTAMP(6) WITH TIME ZONE,
    date_validation TIMESTAMP(6) WITH TIME ZONE,
    formula_id BIGINT,
    mac_envoye VARCHAR(255),
    mac_recu VARCHAR(255),
    montant VARCHAR(255),
    raw_return_params TEXT,
    reference VARCHAR(255),
    status VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT payment_status_check
        CHECK (((status)::TEXT = ANY ((ARRAY[
            'PENDING'::VARCHAR,
            'SUCCESS'::VARCHAR,
            'FAILED'::VARCHAR,
            'INVALID_SIGNATURE'::VARCHAR
        ])::TEXT[])))
);

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);
